name: AppServiceApp Basic Deployment

on:
  push:
    branch:
      - home

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip static files
        run: zip -r app.zip ./frontend


