name: Push to Container Registry

on:
  push:
    branches:
      - home
    paths:
      - 'api/**'

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.AZR_USERNAME }}
          password: ${{ secrets.AZR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.AZR_INFO }}/api:latest
