on:
  push:
    branches:
      - home
      - paths:
        ./frontend

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: home

      - name: Zip content
        run: |
         cd frontend/
         zip -r ../frontend.zip .
         cd ..
      
      - name: List contents of ZIP file
        run: unzip -l frontend.zip


      - name: WebApp Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: mainWebApp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: frontend.zip #needs to specify the file name or it didnt work

      


