on:
  push:
    branches:
      - home

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Zip content
        uses: actions/checkout@v4
        with:
          ref: home
        run: |
          cd frontend/
          zip -r * frontend.zip .
          cd ..

      


